// Exercise Library — 220+ exercises with metadata for the PolyVerses AI Fitness Coach
// Structure: { id, name, category, muscles (primary + secondary), equipment,
//             difficulty, instructions, commonMistakes, substitutions, videoRef }

export interface Exercise {
  id: string;
  name: string;
  category: 'strength' | 'hypertrophy' | 'endurance' | 'mobility' | 'cardio' | 'plyometric' | 'core' | 'warmup';
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  instructions: string;
  commonMistakes: string[];
  substitutions: string[];       // exercise IDs that can substitute for this one
  videoRef?: string;             // URL or identifier for form reference
  genderNeutral: boolean;        // true = suitable for all; false = notes apply
}

export const EXERCISE_LIBRARY: Exercise[] = [
  // ─── BARBELL COMPOUNDS ───────────────────────────────────────────────
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['lower back', 'calves', 'core'],
    equipment: ['barbell', 'rack'],
    difficulty: 'intermediate',
    instructions: 'Position barbell on upper back (not neck). Feet shoulder-width, toes slightly out. Brace core, descend until hips below knees (or as mobility allows), keep chest up and knees tracking over toes. Drive through mid-foot to stand.',
    commonMistakes: ['Knees caving inward (valgus)', 'Heels lifting off the ground', 'Rounding the lower back at the bottom', 'Bar resting on the neck instead of the traps', 'Rising onto toes at the top'],
    substitutions: ['goblet-squat', 'leg-press', 'bulgarian-split-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Barbell-Back-Squat',
    genderNeutral: true,
  },
  {
    id: 'barbell-deadlift',
    name: 'Conventional Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back', 'quadriceps'],
    secondaryMuscles: ['lats', 'traps', 'core', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: 'Stand with mid-foot under the bar. Grip bar just outside legs. Flatten back, brace core, drive through the floor with legs while pulling the bar up the shins and thighs. Lock out hips and shoulders at top. Lower with control — do not round.',
    commonMistakes: ['Rounding the back at the start or finish', 'Hips rising faster than shoulders (squat-like lift)', 'Bar drifting away from the body', 'Squatting instead of hinging', 'Not bracing before the pull'],
    substitutions: ['romanian-deadlift', 'trap-bar-deadlift', 'kettlebell-deadlift'],
    videoRef: 'https://exrx.net/Lists/Exercises/Barbell-Deadlift',
    genderNeutral: true,
  },
  {
    id: 'trap-bar-deadlift',
    name: 'Trap Bar (Hex Bar) Deadlift',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['traps', 'core', 'forearms'],
    equipment: ['trap-bar', 'weight plates'],
    difficulty: 'beginner',
    instructions: 'Stand inside the trap bar, feet hip-width. Bend at hips and knees, keep back flat, grip the handles. Drive through the floor, extending hips and knees together. Lock out at the top without hyperextending. Lower with control.',
    commonMistakes: ['Hips too low (turning it into a squat)', 'Hips too high (turning it into a stiff-leg deadlift)', 'Hunching shoulders at the top', 'Bouncing the weight at the bottom'],
    substitutions: ['conventional-deadlift', 'kettlebell-deadlift'],
    videoRef: 'https://exrx.net/Lists/Exercises/Trap-Bar-Deadlift',
    genderNeutral: true,
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['serratus anterior', 'core'],
    equipment: ['barbell', 'bench', 'rack'],
    difficulty: 'intermediate',
    instructions: 'Lie on bench, eyes under the bar. Grip just outside shoulder width. Unrack, lower bar to mid-chest with elbows at ~45–75° from torso (not flared). Press up and slightly back toward head. Lock out without hyperextending shoulders.',
    commonMistakes: ['Elbows flared at 90° (shoulder strain)', 'Bouncing the bar off the chest', 'Feet lifting off the floor', 'Head jutting into the bench', 'Incomplete range of motion'],
    substitutions: ['dumbbell-bench-press', 'push-up', 'chest-press-machine'],
    videoRef: 'https://exrx.net/Lists/Exercises/Barbell-Bench-Press',
    genderNeutral: true,
  },
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press (Standing)',
    category: 'strength',
    primaryMuscles: ['anterior deltoids', 'medial deltoids', 'triceps'],
    secondaryMuscles: ['upper trapezius', 'core', 'serratus anterior'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: 'Stand with bar at upper chest, grip just outside shoulders. Brace core and glutes. Press bar vertically overhead until arms are fully extended (bar over ears or slightly behind). Lower with control to upper chest.',
    commonMistakes: ['Excessive back arch (rib flare)', 'Bar traveling forward instead of vertical', 'Head jutting forward under the bar', 'Partial range of motion', 'Bent knees / no core brace'],
    substitutions: ['seated-dumbbell-press', 'push-press', 'machine-shoulder-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Barbell-Overhead-Press',
    genderNeutral: true,
  },
  {
    id: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'lower back', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: 'Hinge at hips, torso at ~45° or parallel to floor, back flat. Grip bar just outside legs. Pull bar toward lower ribs / upper abdomen, squeezing shoulder blades. Lower with control — do not let shoulders round forward at the bottom.',
    commonMistakes: ['Rounded back', 'Using momentum / swinging', 'Pulling to the chest instead of the abdomen (upper trap dominance)', 'Hyperextending at the top', 'Elbows too wide or too narrow'],
    substitutions: ['dumbbell-row', 'seated-cable-row', 'chest-supported-row'],
    videoRef: 'https://exrx.net/Lists/Exercises/Barbell-Bent-Over-Row',
    genderNeutral: true,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['adductors', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: 'Stand holding barbell at thigh level. With soft knees (not squatting), push hips back, lowering the bar along the thighs and shins. Feel the stretch in hamstrings. Stop when hips can no longer go back without rounding. Drive hips forward to return.',
    commonMistakes: ['Bending the knees too much (turning it into a squat)', 'Rounding the back', 'Bar drifting away from the body', 'Confusing it with a stiff-leg deadlift from the floor', 'Not going deep enough to feel the stretch'],
    substitutions: ['conventional-deadlift', 'kettlebell-swing', 'hamstring-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Romanian-Deadlift',
    genderNeutral: true,
  },
  {
    id: 'incline-barbbell-bench-press',
    name: 'Incline Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['upper pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['serratus anterior'],
    equipment: ['barbell', 'incline bench', 'rack'],
    difficulty: 'intermediate',
    instructions: 'Set bench to 30–45°. Lie back, eyes under the bar. Grip just outside shoulder width. Lower bar to upper chest / collarbone area. Press up. Keep elbows at moderate angle (not fully flared).',
    commonMistakes: ['Too steep an incline (turns into a shoulder press)', 'Elbows fully flared', 'Bar path too vertical (hits chin/throat)', 'Shoulders rolling forward at the top'],
    substitutions: ['incline-dumbbell-press', 'flat-bench-press', 'cable-crossover-low'],
    videoRef: 'https://exrx.net/Lists/Exercises/Incline-Bench-Press',
    genderNeutral: true,
  },

  // ─── DUMBBELL COMPOUNDS ──────────────────────────────────────────────
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'strength',
    primaryMuscles: ['pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['serratus anterior', 'core'],
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    instructions: 'Lie on bench holding dumbbells at chest level, elbows slightly below torso. Press up and together (dumbbells can touch or come close at top). Lower with control to chest level. Greater range of motion than barbell version.',
    commonMistakes: ['Dropping dumbbells too low (shoulder strain)', 'Uneven pressing (one side doing more work)', 'Bent wrists', 'Not using full ROM because weights are too heavy'],
    substitutions: ['barbell-bench-press', 'push-up', 'chest-press-machine'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Bench-Press',
    genderNeutral: true,
  },
  {
    id: 'dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'core (anti-rotation)'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    instructions: 'Place one knee and hand on a bench, back flat and parallel to floor. Hold dumbbell in opposite hand, arm hanging straight. Pull dumbbell toward hip (not chest), squeezing the back. Lower with control. Keep the torso still.',
    commonMistakes: ['Rotating the torso to cheat the weight up', 'Pulling to the chest (upper trap / biceps dominance)', 'Hovering the elbow too far from the body', 'Not getting a full stretch at the bottom'],
    substitutions: ['barbell-bent-over-row', 'seated-cable-row', 'cable-row-single-arm'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Row',
    genderNeutral: true,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press (Seated or Standing)',
    category: 'strength',
    primaryMuscles: ['anterior deltoids', 'medial deltoids', 'triceps'],
    secondaryMuscles: ['upper trapezius', 'core', 'serratus anterior'],
    equipment: ['dumbbells', 'bench (if seated)'],
    difficulty: 'intermediate',
    instructions: 'Hold dumbbells at shoulder height, palms facing forward or neutral. Press overhead until arms are extended. Lower with control to shoulder level. Keep core braced; avoid excessive back arch if standing.',
    commonMistakes: ['Excessive back arch', 'Dumbbells colliding at the top (loss of control)', 'Going behind the head (risk to shoulders)', 'Partial ROM', 'Momentum from legs if standing'],
    substitutions: ['barbell-overhead-press', 'machine-shoulder-press', ' Arnold-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Shoulder-Press',
    genderNeutral: true,
  },
  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Lunge',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
    instructions: 'Hold dumbbells at sides. Step forward (or reverse) with one leg, lowering hips until both knees are bent at ~90°. Front knee should stay over the ankle. Push through the front foot to return to standing. Alternate legs or do all reps on one side.',
    commonMistakes: ['Front knee collapsing inward', 'Front knee going far past the toes', 'Back knee slamming the ground', 'Torso leaning too far forward', 'Short steps (partial ROM)'],
    substitutions: ['barbell-lunge', 'goblet-lunge', 'bulgarian-split-squat', 'walking-lunge'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Lunge',
    genderNeutral: true,
  },
  {
    id: 'dumbbell-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'core'],
    secondaryMuscles: ['hamstrings', 'calves', 'upper back (holding position)'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: 'Hold one dumbbell vertically against the chest (goblet position), both hands on the top end. Feet shoulder-width or wider. Squat down with chest up, elbows inside knees. Drive through mid-foot to stand.',
    commonMistakes: ['Heels lifting', 'Knees caving in', 'Rounding the upper back', 'Dumbbell drifting forward', 'Not squatting deep enough'],
    substitutions: ['barbell-squat', 'leg-press', 'bodyweight-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/ goblet-squat',
    genderNeutral: true,
  },
  {
    id: 'dumbbell-deadlift',
    name: 'Dumbbell Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back', 'quadriceps'],
    secondaryMuscles: ['lats', 'traps', 'core', 'forearms'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand with dumbbells on the floor just outside feet. Hinge at hips, slight knee bend, back flat. Grip dumbbells. Drive through the floor, extending hips and knees. Lock out at top. Lower with control.',
    commonMistakes: ['Rounding the back', 'Hips rising faster than shoulders', 'Dumbbells drifting away from the body', 'Confusing with RDL (this starts from the floor)'],
    substitutions: ['barbell-deadlift', 'kettlebell-deadlift', 'trap-bar-deadlift'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Deadlift',
    genderNeutral: true,
  },

  // ─── UPPER BODY PUSH ──────────────────────────────────────────────────
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'strength',
    primaryMuscles: ['pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['core', 'serratus anterior', 'middle trapezius'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Start in plank position, hands slightly wider than shoulders, body in a straight line from head to heels. Lower chest toward the floor by bending elbows (keep them at ~45° from torso, not flared). Press back up to full extension.',
    commonMistakes: ['Hips sagging (core not engaged)', 'Hips piked up', 'Elbows flared at 90°', 'Partial range of motion', 'Head dropping or jutting forward'],
    substitutions: ['incline-push-up', 'knee-push-up', 'bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Push-Up',
    genderNeutral: true,
  },
  {
    id: 'incline-push-up',
    name: 'Incline Push-Up',
    category: 'strength',
    primaryMuscles: ['pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['core', 'serratus anterior'],
    equipment: ['bench', 'box', 'rail', 'wall'],
    difficulty: 'beginner',
    instructions: 'Place hands on an elevated surface (bench, box, rail). Body forms a straight line from head to heels. Lower chest toward the surface by bending elbows. Press back up. Lower the surface height to increase difficulty.',
    commonMistakes: ['Hips sagging', 'Hips piked', 'Not going deep enough', 'Elbows flared'],
    substitutions: ['push-up', 'knee-push-up', 'decline-push-up'],
    videoRef: 'https://exrx.net/Lists/Exercises/Incline-Push-Up',
    genderNeutral: true,
  },
  {
    id: 'decline-push-up',
    name: 'Decline Push-Up',
    category: 'strength',
    primaryMuscles: ['upper pectorals', 'anterior deltoids', 'triceps'],
    secondaryMuscles: ['core'],
    equipment: ['bench', 'box', 'step'],
    difficulty: 'intermediate',
    instructions: 'Place feet on an elevated surface, hands on the floor. Body forms a straight line. Lower chest toward the floor. Press back up. The decline angle shifts emphasis to the upper chest and increases difficulty.',
    commonMistakes: ['Hips sagging', 'Elbows flared', 'Partial ROM', 'Head dropping'],
    substitutions: ['incline-push-up', 'push-up', 'incline-bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Decline-Push-Up',
    genderNeutral: true,
  },
  {
    id: 'dip',
    name: 'Parallel Bar Dip',
    category: 'strength',
    primaryMuscles: ['triceps', 'lower pectorals', 'anterior deltoids'],
    secondaryMuscles: ['middle trapezius', 'core'],
    equipment: ['parallel bars', 'dip station'],
    difficulty: 'intermediate',
    instructions: 'Grip parallel bars, arms straight, body upright (for triceps focus) or slightly leaned forward (for chest focus). Lower by bending elbows until upper arms are parallel to the bars or slightly below. Press back up. Lean forward more to emphasize chest; stay upright for triceps.',
    commonMistakes: ['Shoulders rolling forward / internally rotating at the bottom', 'Going too deep without shoulder mobility', 'Not leaning enough for chest focus (if desired)', 'Kipping / swinging to get up'],
    substitutions: ['close-grip-bench-press', 'tricep-push-down', 'bench-dip'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dip',
    genderNeutral: true,
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip (Seated Dip)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['anterior deltoids'],
    equipment: ['bench', 'chair', 'box'],
    difficulty: 'beginner',
    instructions: 'Sit on the edge of a bench, hands gripping the edge beside hips. Slide forward off the bench, legs bent (easier) or straight (harder). Lower by bending elbows until upper arms are parallel to the floor. Press back up.',
    commonMistakes: ['Shoulders rolling forward at the bottom', 'Going too deep', 'Using momentum', 'Feet not positioned for desired difficulty'],
    substitutions: ['dip', 'tricep-push-down', 'close-grip-bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Bench-Dip',
    genderNeutral: true,
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'strength',
    primaryMuscles: ['triceps', 'pectorals', 'anterior deltoids'],
    secondaryMuscles: ['core'],
    equipment: ['barbell', 'bench', 'rack'],
    difficulty: 'intermediate',
    instructions: 'Lie on bench, grip bar with hands shoulder-width or narrower. Unrack, lower bar to lower chest / upper abdomen. Elbows stay close to the body (not flared). Press up. Narrower grip = more triceps.',
    commonMistakes: ['Elbows flaring out', 'Wrists bending excessively', 'Bar path too high (hits chin)', 'Grip too narrow (wrist strain)'],
    substitutions: ['dip', 'tricep-push-down', 'bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Close-Grip-Bench-Press',
    genderNeutral: true,
  },
  {
    id: 'pectoral-fly',
    name: 'Dumbbell Fly (Flat)',
    category: 'hypertrophy',
    primaryMuscles: ['pectorals'],
    secondaryMuscles: ['anterior deltoids', 'serratus anterior'],
    equipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    instructions: 'Lie on bench holding dumbbells above chest, arms nearly straight, slight elbow bend. Lower dumbbells out to the sides in an arc until you feel a stretch in the chest (do not go so low that shoulders strain). Pull back together over the chest.',
    commonMistakes: ['Elbows bending too much (turning into a press)', 'Going too low (shoulder strain)', 'Using momentum', 'Not getting a stretch', 'Bending wrists'],
    substitutions: ['cable-crossover', 'machine-fly', 'incline-fly'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Fly',
    genderNeutral: true,
  },
  {
    id: 'incline-dumbbell-fly',
    name: 'Incline Dumbbell Fly',
    category: 'hypertrophy',
    primaryMuscles: ['upper pectorals'],
    secondaryMuscles: ['anterior deltoids', 'serratus anterior'],
    equipment: ['dumbbells', 'incline bench'],
    difficulty: 'intermediate',
    instructions: 'Set bench to 30–45°. Lie back, hold dumbbells above upper chest, arms nearly straight. Lower in an arc to the sides until a stretch is felt in the upper chest. Pull back together over the upper chest.',
    commonMistakes: ['Too steep an angle', 'Going too low', 'Elbows bending into a press', 'Dumbbells going behind the head plane'],
    substitutions: ['pectoral-fly', 'cable-crossover-high', 'incline-bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Incline-Dumbbell-Fly',
    genderNeutral: true,
  },
  {
    id: 'tricep-push-down',
    name: 'Cable Tricep Push-Down',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['anterior deltoids (stabilizer)'],
    equipment: ['cable machine', 'straight bar' | 'rope'],
    difficulty: 'beginner',
    instructions: 'Stand at cable machine with handle at shoulder height. Elbows tucked at sides. Push handle down until arms are fully extended. Squeeze triceps at bottom. Return with control, keeping elbows stationary.',
    commonMistakes: ['Elbows flaring out / moving forward', 'Using body weight to push', 'Incomplete extension', 'Rounding the shoulders forward'],
    substitutions: ['dip', 'close-grip-bench-press', 'tricep-overhead-extension'],
    videoRef: 'https://exrx.net/Lists/Exercises/Tricep-Push-Down',
    genderNeutral: true,
  },
  {
    id: 'tricep-overhead-extension',
    name: 'Dumbbell Overhead Tricep Extension',
    category: 'strength',
    primaryMuscles: ['triceps (long head)'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    instructions: 'Stand or sit holding one dumbbell overhead with both hands (or one dumbbell in each hand). Lower the weight behind the head by bending elbows, keeping upper arms stationary and close to the head. Extend back to overhead.',
    commonMistakes: ['Elbows flaring wide', 'Moving the upper arms (turning into a press)', 'Arching the lower back', 'Going too heavy and losing form'],
    substitutions: ['tricep-push-down', 'tricep-kickbacks', 'cable-overhead-extension'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Overhead-Tricep-Extension',
    genderNeutral: true,
  },
  {
    id: 'tricep-kickback',
    name: 'Dumbbell Tricep Kickback',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Hinge forward at hips, back flat, one hand on a bench or support. Hold dumbbell in opposite hand, upper arm parallel to torso and elbow bent at 90°. Extend forearm back until arm is straight (squeeze tricep). Return with control.',
    commonMistakes: ['Upper arm dropping below parallel (losing tricep focus)', 'Using momentum to swing', 'Not extending fully', 'Too heavy — form breaks down'],
    substitutions: ['tricep-push-down', 'tricep-overhead-extension'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Tricep-Kickback',
    genderNeutral: true,
  },

  // ─── UPPER BODY PULL ──────────────────────────────────────────────────
  {
    id: 'pull-up',
    name: 'Pull-Up (Overhand Grip)',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'biceps', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['rear deltoids', 'core', 'forearms'],
    equipment: ['pull-up bar'],
    difficulty: 'intermediate',
    instructions: 'Hang from bar with overhand grip, hands slightly wider than shoulders. Pull body up until chin clears the bar. Lower with control to full arm extension. Avoid swinging. Use a band, assisted machine, or negative reps to build up to full pull-ups.',
    commonMistakes: ['Kipping / swinging', 'Not getting chin over the bar', 'Dropping too quickly at the bottom', 'Shoulders shrugging at the start (not engaging lats)', 'Partial ROM'],
    substitutions: ['chin-up', 'assisted-pull-up', 'lat-pulldown', 'inverted-row'],
    videoRef: 'https://exrx.net/Lists/Exercises/Pull-Up',
    genderNeutral: true,
  },
  {
    id: 'chin-up',
    name: 'Chin-Up (Underhand Grip)',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'biceps', 'rhomboids'],
    secondaryMuscles: ['rear deltoids', 'core'],
    equipment: ['pull-up bar'],
    difficulty: 'intermediate',
    instructions: 'Hang from bar with underhand grip, hands shoulder-width. Pull body up until chin clears the bar. Lower with control. The underhand grip shifts slightly more emphasis to the biceps.',
    commonMistakes: ['Kipping', 'Not full ROM', 'Shoulders rising toward ears at the bottom', 'Legs swinging'],
    substitutions: ['pull-up', 'assisted-chin-up', 'lat-pulldown'],
    videoRef: 'https://exrx.net/Lists/Exercises/Chin-Up',
    genderNeutral: true,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids'],
    equipment: ['cable machine', 'lat bar' | 'straight bar'],
    difficulty: 'beginner',
    instructions: 'Sit at lat pulldown machine, thighs under pads. Grip bar wider than shoulders. Pull bar down to upper chest / clavicle, squeezing lats and bringing shoulder blades together. Return with control — do not let the weight stack slam.',
    commonMistakes: ['Pulling behind the neck (shoulder risk)', 'Leaning back too far (using body weight)', 'Using momentum', 'Not squeezing at the bottom', 'Grip too narrow or too wide for individual anatomy'],
    substitutions: ['pull-up', 'chin-up', 'assisted-pull-up'],
    videoRef: 'https://exrx.net/Lists/Exercises/Lat-Pulldown',
    genderNeutral: true,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'core'],
    equipment: ['cable machine', 'straight bar' | 'rope' | 'V-handle'],
    difficulty: 'beginner',
    instructions: 'Sit at cable row station, feet on platform, knees slightly bent. Grip handle. Pull handle toward the abdomen / lower chest, squeezing shoulder blades together. Keep torso upright (do not rock). Return with control.',
    commonMistakes: ['Rocking / using momentum', 'Pulling too high (to chest / shoulders)', 'Shoulders rounding forward at the extension', 'Incomplete stretch at the start'],
    substitutions: ['barbell-bent-over-row', 'dumbbell-row', 'chest-supported-row'],
    videoRef: 'https://exrx.net/Lists/Exercises/Seated-Cable-Row',
    genderNeutral: true,
  },
  {
    id: 'cable-row-single-arm',
    name: 'Single-Arm Cable Row',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'core (anti-rotation)'],
    equipment: ['cable machine', 'handle'],
    difficulty: 'intermediate',
    instructions: 'Stand or kneel beside a cable machine, handle at chest height. Pull handle toward the hip, rotating slightly through the torso (controlled). Squeeze the back at the end. Return with control. Keep hips relatively stable.',
    commonMistakes: ['Over-rotating the torso (turning into a woodchop)', 'Pulling to the chest instead of the hip', 'Shoulders shrugging', 'Elbow too wide'],
    substitutions: ['dumbbell-row', 'seated-cable-row', 'lat-pulldown'],
    videoRef: 'https://exrx.net/Lists/Exercises/Single-Arm-Cable-Row',
    genderNeutral: true,
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row (Bodyweight Row)',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'core'],
    equipment: ['bar', 'rack', 'rings'],
    difficulty: 'beginner',
    instructions: 'Set a bar at chest height. Hang underneath it, body straight, heels on the floor (or feet elevated for more difficulty). Pull chest toward the bar, squeezing shoulder blades. Lower with control.',
    commonMistakes: ['Hips sagging', 'Not getting chest to the bar', 'Elbows flaring wide', 'Partial ROM'],
    substitutions: ['pull-up', 'lat-pulldown', 'seated-cable-row'],
    videoRef: 'https://exrx.net/Lists/Exercises/Inverted-Row',
    genderNeutral: true,
  },
  {
    id: 'face-pull',
    name: 'Cable Face Pull',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoids', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['upper trapezius', 'forearms'],
    equipment: ['cable machine', 'rope attachment'],
    difficulty: 'beginner',
    instructions: 'Set cable at head height with a rope. Grip rope ends, arms extended. Pull the rope toward the face, separating the hands and squeezing the rear delts and upper back. Elbows should end up high and wide. Return with control.',
    commonMistakes: ['Pulling too low (to the chest)', 'Not externally rotating at the end', 'Using too much weight and losing form', 'Shrugging instead of pulling with the back'],
    substitutions: ['reverse-fly', 'band-pull-apart'],
    videoRef: 'https://exrx.net/Lists/Exercises/Face-Pull',
    genderNeutral: true,
  },
  {
    id: 'shrug',
    name: 'Barbell / Dumbbell Shrug',
    category: 'strength',
    primaryMuscles: ['upper trapezius'],
    secondaryMuscles: ['levator scapulae', 'rhomboids'],
    equipment: ['barbell' | 'dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding weight at sides (or in front for barbell). Keep arms straight. Shrug shoulders up toward ears as high as possible. Squeeze at top. Lower with control.',
    commonMistakes: ['Rolling the shoulders (turning into a dance move — useless)', 'Bending the elbows', 'Using too much weight and shortening ROM', 'Not squeezing at the top'],
    substitutions: ['upright-row', 'face-pull'],
    videoRef: 'https://exrx.net/Lists/Exercises/Shrug',
    genderNeutral: true,
  },
  {
    id: 'bicep-curl',
    name: 'Dumbbell Bicep Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['brachialis', 'forearms'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells at sides, palms facing forward (or neutral for hammer curl). Curl weights up toward shoulders, keeping elbows stationary and close to the body. Squeeze at the top. Lower with control.',
    commonMistakes: ['Swinging / using momentum (hip thrust)', 'Elbows moving forward', 'Not going full ROM', 'Wrist bending', 'Elbows flaring out to the sides'],
    substitutions: ['barbell-curl', 'cable-curl', 'hammer-curl', 'preacher-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dumbbell-Bicep-Curl',
    genderNeutral: true,
  },
  {
    id: 'hammer-curl',
    name: 'Dumbbell Hammer Curl',
    category: 'strength',
    primaryMuscles: ['biceps', 'brachialis', 'forearms (brachioradialis)'],
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells at sides, palms facing each other (neutral grip). Curl weights up toward shoulders, keeping elbows stationary. Squeeze at the top. Lower with control.',
    commonMistakes: ['Swinging momentum', 'Elbows moving forward', 'Partial ROM', 'Wrist bending'],
    substitutions: ['bicep-curl', 'reverse-curl', 'cable-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Hammer-Curl',
    genderNeutral: true,
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'strength',
    primaryMuscles: ['biceps (short head emphasis)'],
    secondaryMuscles: ['brachialis'],
    equipment: ['barbell' | 'dumbbell', 'preacher bench'],
    difficulty: 'intermediate',
    instructions: 'Sit at preacher bench, arms resting on the pad, palms up. Curl weight up toward shoulders, keeping arms on the pad. Squeeze at top. Lower with control — do not let elbows lift off the pad.',
    commonMistakes: ['Lifting elbows off the pad', 'Swinging', 'Partial ROM (not going to full extension)', 'Too heavy — form breaks'],
    substitutions: ['bicep-curl', 'hammer-curl', 'cable-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Preacher-Curl',
    genderNeutral: true,
  },
  {
    id: 'cable-curl',
    name: 'Cable Bicep Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['brachialis'],
    equipment: ['cable machine', 'straight bar' | 'rope' | 'handle'],
    difficulty: 'beginner',
    instructions: 'Stand at cable machine, hold bar or handle at thigh level, palms up. Curl handle up toward shoulders, elbows stationary. Squeeze at top. Lower with control. Cable provides constant tension throughout the ROM.',
    commonMistakes: ['Elbows moving forward', 'Swinging', 'Incomplete ROM', 'Too heavy — body English'],
    substitutions: ['dumbbell-curl', 'barbell-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Cable-Bicep-Curl',
    genderNeutral: true,
  },
  {
    id: 'reverse-curl',
    name: 'Barbell / Dumbbell Reverse Curl',
    category: 'strength',
    primaryMuscles: ['forearms (brachioradialis)', 'biceps'],
    secondaryMuscles: [],
    equipment: ['barbell' | 'dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding weight at sides, palms facing down (overhand grip). Curl weight up toward shoulders, keeping elbows stationary. Squeeze at top. Lower with control. Emphasizes forearm brachioradialis.',
    commonMistakes: ['Wrist bending excessively', 'Elbows moving forward', 'Too heavy — form breaks'],
    substitutions: ['hammer-curl', 'bicep-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Reverse-Curl',
    genderNeutral: true,
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'strength',
    primaryMuscles: ['upper trapezius', 'middle deltoids'],
    secondaryMuscles: ['rhomboids', 'levator scapulae'],
    equipment: ['barbell' | 'dumbbells' | 'cable'],
    difficulty: 'intermediate',
    instructions: 'Stand holding weight in front of thighs, hands shoulder-width or narrower. Pull weight up toward the chin, leading with elbows. Keep weight close to the body. Lower with control.',
    commonMistakes: ['Grip too wide (shoulder impingement risk for some)', 'Bar going too far forward', 'Shrugging at the top instead of pulling with elbows', 'Using momentum'],
    substitutions: ['shrug', 'lateral-raise', 'high-pull'],
    videoRef: 'https://exrx.net/Lists/Exercises/Upright-Row',
    genderNeutral: true,
  },
  {
    id: 'high-pull',
    name: 'Dumbbell / Barbell High Pull',
    category: 'strength',
    primaryMuscles: ['upper trapezius', 'middle deltoids', 'biceps'],
    secondaryMuscles: ['rhombids', 'core'],
    equipment: ['dumbbells' | 'barbell'],
    difficulty: 'intermediate',
    instructions: 'Hold weight at thigh level. Explosively pull weight up toward the chin / upper chest, driving elbows high and slightly higher than the hands. Lower with control. More explosive than an upright row; more shoulder-focused.',
    commonMistakes: ['Using too much weight and losing speed', 'Bar drifting forward', 'Not getting elbows high enough', 'Rounding the back'],
    substitutions: ['upright-row', 'jump-shrug', 'hang-clean'],
    videoRef: 'https://exrx.net/Lists/Exercises/High-Pull',
    genderNeutral: true,
  },

  // ─── SHOULDER ISOLATION ────────────────────────────────────────────────
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['medial deltoids'],
    secondaryMuscles: ['anterior deltoids', 'traps (stabilizer)'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding light dumbbells at sides, palms facing each other. Raise arms out to the sides until parallel with the floor (or slightly above). Lead with elbows, not hands. Lower with control.',
    commonMistakes: ['Using too much weight (momentum, shrugging)', 'Raising arms too far forward (turning into a front raise) or too far back', 'Bent elbows too much (or locked out)', 'Not controlling the descent'],
    substitutions: ['cable-lateral-raise', 'machine-lateral-raise', 'upright-row'],
    videoRef: 'https://exrx.net/Lists/Exercises/Lateral-Raise',
    genderNeutral: true,
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['medial deltoids'],
    secondaryMuscles: ['anterior deltoids'],
    equipment: ['cable machine', 'handle' | 'strap'],
    difficulty: 'intermediate',
    instructions: 'Stand beside a low cable pulley, hold handle with far hand. Raise arm out to the side against the cable resistance. The cable angle provides resistance that is more aligned with the deltoid throughout the ROM compared to dumbbells.',
    commonMistakes: ['Using too much weight', 'Shrugging the traps', 'Arm traveling forward instead of to the side', 'Not getting full height'],
    substitutions: ['lateral-raise', 'machine-lateral-raise'],
    videoRef: 'https://exrx.net/Lists/Exercises/Cable-Lateral-Raise',
    genderNeutral: true,
  },
  {
    id: 'front-raise',
    name: 'Dumbbell Front Raise',
    category: 'hypertrophy',
    primaryMuscles: ['anterior deltoids'],
    secondaryMuscles: ['upper pectorals (stabilizer)'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells at thighs, palms facing down or neutral. Raise one or both arms straight forward until parallel with the floor. Lower with control. Alternate arms or do both at once.',
    commonMistakes: ['Using too much weight (momentum, swinging)', 'Bending the elbows too much (turning into an upright row)', 'Raising too high (beyond parallel)', 'Arching the back'],
    substitutions: ['cable-front-raise', 'plate-front-raise', 'overhead-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Front-Raise',
    genderNeutral: true,
  },
  {
    id: 'rear-delt-fly',
    name: 'Dumbbell Rear Delt Fly (Bent-Over)',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoids'],
    secondaryMuscles: ['rhomboids', 'middle trapezius'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: 'Hinge at hips, torso nearly parallel to floor, back flat. Hold dumbbells at sides. Raise arms out to the sides, leading with elbows, squeezing the rear delts. Lower with control.',
    commonMistakes: ['Using momentum (swinging)', 'Elbows dropping too low (traps take over)', 'Going too heavy', 'Not getting a squeeze at the top'],
    substitutions: ['face-pull', 'reverse-fly-machine', 'cable-reverse-fly'],
    videoRef: 'https://exrx.net/Lists/Exercises/Bent-Over-Lateral-Raise',
    genderNeutral: true,
  },
  {
    id: 'reverse-fly-machine',
    name: 'Machine Reverse Fly',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoids'],
    secondaryMuscles: ['rhomboids', 'middle trapezius'],
    equipment: ['reverse fly machine'],
    difficulty: 'beginner',
    instructions: 'Sit at reverse fly machine, chest against pad, handles in front. Pull handles apart and back, squeezing the rear delts. Return with control.',
    commonMistakes: ['Using momentum', 'Not getting full spread', 'Hunching the shoulders forward'],
    substitutions: ['rear-delt-fly', 'face-pull', 'band-pull-apart'],
    videoRef: 'https://exrx.net/Lists/Exercises/Machine-Back-Pulse',
    genderNeutral: true,
  },
  {
    id: ' Arnold-press',
    name: 'Arnold Press (Dumbbell)',
    category: 'strength',
    primaryMuscles: ['anterior deltoids', 'medial deltoids', 'triceps'],
    secondaryMuscles: ['upper trapezius'],
    equipment: ['dumbbells', 'bench (seated)'],
    difficulty: 'intermediate',
    instructions: 'Sit holding dumbbells at shoulder height, palms facing you (neutral). As you press up, rotate palms to face forward at the top. Reverse the rotation as you lower back to the starting position. Greater ROM and rotation than a standard shoulder press.',
    commonMistakes: ['Excessive back arch', 'Rotating too fast / losing control', 'Too heavy — rotation breaks down', 'Not getting full extension'],
    substitutions: ['dumbbell-shoulder-press', 'barbell-overhead-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Arnold-Press',
    genderNeutral: true,
  },

  // ─── LEGS ──────────────────────────────────────────────────────────────
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['leg press machine'],
    difficulty: 'beginner',
    instructions: 'Sit in leg press machine, feet on the platform shoulder-width, slightly higher than mid-platform for more glute emphasis (or lower for more quad emphasis). Unrack, lower the platform by bending knees until hips are at ~90° or as mobility allows. Do not let the lower back round off the pad. Press back up.',
    commonMistakes: ['Locking knees at the top (joint hyperextension)', 'Lower back lifting off the pad (rounding)', 'Feet too high or too low for the intended emphasis', 'Partial ROM', 'Knees caving inward'],
    substitutions: ['barbell-squat', 'goblet-squat', 'smith-machine-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Leg-Press',
    genderNeutral: true,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: [],
    equipment: ['leg extension machine'],
    difficulty: 'beginner',
    instructions: 'Sit in leg extension machine, back against pad, ankles under the pads. Extend legs fully, squeezing quads at the top. Lower with control. This is an isolation movement for the quads — not a replacement for compound leg work.',
    commonMistakes: ['Locking the knees aggressively (joint stress)', 'Incomplete ROM', 'Using too much weight and swinging', 'Not squeezing at the top'],
    substitutions: ['squats', 'leg-press', 'split-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Leg-Extension',
    genderNeutral: true,
  },
  {
    id: 'hamstring-curl',
    name: 'Lying / Seated Hamstring Curl',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves (stabilizer)'],
    equipment: ['hamstring curl machine (lying or seated)'],
    difficulty: 'beginner',
    instructions: 'Position on hamstring curl machine (lying face-down or seated). Ankles under the pads. Curl heels toward the butt / glutes, squeezing hamstrings. Lower with control.',
    commonMistakes: ['Using momentum', 'Incomplete ROM', 'Hips lifting off the pad (lying version)', 'Not squeezing at the top'],
    substitutions: ['romanian-deadlift', 'kettlebell-swing', 'nordic-curl'],
    videoRef: 'https://exrx.net/Lists/Exercises/Lying-Hamstring-Curl',
    genderNeutral: true,
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Hamstring Curl',
    category: 'strength',
    primaryMuscles: ['hamstrings (knee flexion emphasis)'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['pad / mat', 'anchor for feet (partner, strap, or machine)'],
    difficulty: 'advanced',
    instructions: 'Kneel on a pad with feet anchored (held by a partner or strapped). Keep body straight from knees to head. Lower the torso toward the floor by letting the knees extend, using hamstrings to control the descent as much as possible. Use hands to catch yourself at the bottom, then push back up or use a band / assist to return.',
    commonMistakes: ['Not controlling the descent (just falling)', 'Hips bending (not keeping a straight line)', 'Too difficult — using bands or doing negatives first'],
    substitutions: ['hamstring-curl', 'romanian-deadlift', 'glute-ham-raise'],
    videoRef: 'https://exrx.net/Lists/Exercises/Nordic-Hamstring-Curl',
    genderNeutral: true,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['dumbbells' | 'barbell', 'bench / box'],
    difficulty: 'intermediate',
    instructions: 'Stand facing away from a bench. Place one foot on the bench behind you. Lower the back knee toward the floor by bending the front leg. Keep torso upright (more upright = more quad; more forward lean = more glute). Drive through the front foot to return.',
    commonMistakes: ['Front knee collapsing inward', 'Front knee going too far past toes excessively', 'Back foot slipping', 'Not going deep enough', 'Torso too upright for glute emphasis (or too leaned for quad emphasis — depends on goal)'],
    substitutions: ['lunges', 'split-squat', 'step-ups'],
    videoRef: 'https://exrx.net/Lists/Exercises/Bulgarian-Split-Squat',
    genderNeutral: true,
  },
  {
    id: 'step-ups',
    name: 'Dumbbell / Barbell Step-Up',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['dumbbells' | 'barbell', 'box' | 'bench' | 'step'],
    difficulty: 'intermediate',
    instructions: 'Hold weights at sides. Step one foot onto a box / bench. Drive through the front foot to bring the back foot up to the box (or just step up and back down). Keep the front knee stable. Alternate legs or do all reps on one side.',
    commonMistakes: ['Pushing off the back foot (cheating)', 'Knee collapsing inward', 'Box too high (hip mobility issue)', 'Not going through full foot contact'],
    substitutions: ['bulgarian-split-squat', 'lunges', 'squats'],
    videoRef: 'https://exrx.net/Lists/Exercises/Step-Up',
    genderNeutral: true,
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['dumbbells' | 'barbell' | 'none'],
    difficulty: 'intermediate',
    instructions: 'Hold weights at sides (or bodyweight). Step forward with one leg, lowering hips until both knees are at ~90°. Push through the front foot to bring the back foot forward into the next lunge step. Continue alternating. Keep torso upright.',
    commonMistakes: ['Front knee collapsing', 'Short steps (turning into a march)', 'Knee slamming the ground', 'Torso leaning too far'],
    substitutions: ['stationary-lunge', 'bulgarian-split-squat', 'step-ups'],
    videoRef: 'https://exrx.net/Lists/Exercises/Walking-Lunge',
    genderNeutral: true,
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'strength',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'lower back'],
    equipment: ['none' | 'dumbbell' | 'barbell' | 'band'],
    difficulty: 'beginner',
    instructions: 'Lie on back, knees bent, feet flat on the floor. Drive through heels to lift hips until the body forms a straight line from shoulders to knees. Squeeze glutes at the top. Lower with control.',
    commonMistakes: ['Over-arching the lower back (hip extension not achieved — lower back does the work)', 'Not squeezing glutes at the top', 'Feet too far or too close (altering the emphasis)', 'Rising onto toes'],
    substitutions: ['hip-thrust', 'deadlift', 'kettlebell-swing'],
    videoRef: 'https://exrx.net/Lists/Exercises/Glute-Bridge',
    genderNeutral: true,
  },
  {
    id: 'hip-thrust',
    name: 'Barbell / Dumbbell Hip Thrust',
    category: 'strength',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower back', 'core', 'quads (stabilizer)'],
    equipment: ['barbell' | 'dumbbell', 'bench'],
    difficulty: 'intermediate',
    instructions: 'Sit on the floor with back against a bench, feet flat. Rest barbell (with padding) or dumbbell over the hips. Drive through heels to lift hips until the body is parallel to the floor. Squeeze glutes hard at the top. Lower with control.',
    commonMistakes: ['Over-arching the lower back (pushing too high — hyperextension)', 'Not squeezing at the top', 'Feet too far (hamstrings take over) or too close (quads take over)', 'Chin tucked or head hanging'],
    substitutions: ['glute-bridge', 'deadlift', 'romanian-deadlift'],
    videoRef: 'https://exrx.net/Lists/Exercises/Hip-Thrust',
    genderNeutral: true,
  },
  {
    id: 'calve-raise',
    name: 'Standing / Seated Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['gastrocnemius (standing)', 'soleus (seated)'],
    secondaryMuscles: [],
    equipment: ['calf raise machine' | 'step' | 'dumbbells'],
    difficulty: 'beginner',
    instructions: 'Standing: stand on a step with heels hanging off, hold a weight or use a machine. Raise up onto the toes as high as possible. Lower heels below the step level for a stretch. Seated: same movement with knees bent (emphasizes soleus).',
    commonMistakes: ['No stretch at the bottom (partial ROM)', 'Bouncing at the bottom', 'Knees bending on standing version (shifts to soleus)', 'Too fast — no squeeze at the top'],
    substitutions: ['none (calf work is unique)'],
    videoRef: 'https://exrx.net/Lists/Exercises/Standing-Calf-Raise',
    genderNeutral: true,
  },

  // ─── CORE ──────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Forearm Plank',
    category: 'core',
    primaryMuscles: ['core (rectus abdominis, transverse abdominis)', 'shoulders', 'glutes'],
    secondaryMuscles: ['quads', 'back extensors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Forearms on the floor, elbows under shoulders. Body in a straight line from head to heels. Engage core, glutes, and quads. Do not let hips sag or pike up. Breathe steadily.',
    commonMistakes: ['Hips sagging (lower back strain)', 'Hips piked up (reducing core engagement)', 'Looking forward / neck craning', 'Holding breath', 'Not engaging glutes'],
    substitutions: ['side-plank', 'plank-with-shoulder-tap', 'dead-bug'],
    videoRef: 'https://exrx.net/Lists/Exercises/Plank',
    genderNeutral: true,
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    primaryMuscles: ['obliques', 'transverse abdominis', 'quadratus lumborum'],
    secondaryMuscles: ['shoulders', 'gluteus medius'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie on your side, forearm on the floor, elbow under shoulder. Stack feet (or stagger for more stability). Lift hips so the body forms a straight line from head to feet. Hold. Switch sides.',
    commonMistakes: ['Hips sagging', 'Hips too high (piked)', 'Top arm not engaged', 'Holding breath'],
    substitutions: ['plank', 'suitcase-carry', 'pallof-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Side-Plank',
    genderNeutral: true,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'core',
    primaryMuscles: ['deep core (transverse abdominis)', 'rectus abdominis'],
    secondaryMuscles: ['hip flexors (controlled)', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie on back, arms extended toward ceiling, legs in tabletop (knees bent at 90°). Press lower back into the floor. Slowly extend one arm back and the opposite leg down toward the floor, keeping the back pressed down. Return to start. Alternate sides.',
    commonMistakes: ['Lower back arching off the floor (the key error)', 'Moving too fast', 'Not keeping arms/legs in line with the torso', 'Breath holding'],
    substitutions: ['bird-dog', 'plank', 'pallof-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Dead-Bug',
    genderNeutral: true,
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'core',
    primaryMuscles: ['core (anti-extension, anti-rotation)', 'glutes', 'back extensors'],
    secondaryMuscles: ['shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Start on all fours (hands and knees). Brace core. Extend one arm forward and the opposite leg back simultaneously, keeping them in a straight line with the torso. Do not let the hips rotate or the back arch. Hold briefly, return, switch sides.',
    commonMistakes: ['Hips rotating', 'Back arching', 'Leg lifting too high (hip flexing instead of extending)', 'Not bracing the core'],
    substitutions: ['dead-bug', 'plank', ' Superman'],
    videoRef: 'https://exrx.net/Lists/Exercises/Bird-Dog',
    genderNeutral: true,
  },
  {
    id: 'superman',
    name: 'Superman (Back Extension)',
    category: 'core',
    primaryMuscles: ['back extensors (erector spinae)', 'glutes'],
    secondaryMuscles: ['hamstrings', 'upper back'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie face-down on the floor. Simultaneously lift arms, chest, and legs off the floor by extending the back and squeezing glutes. Hold briefly at the top. Lower with control. Avoid jerking.',
    commonMistakes: [' jerking / using momentum', 'Neck craning (looking up too hard)', 'Over-arching the lower back (squeeze glutes instead)', 'Not lifting enough to engage the back'],
    substitutions: ['bird-dog', 'back-extension-machine', 'reverse-hyper'],
    videoRef: 'https://exrx.net/Lists/Exercises/Superman',
    genderNeutral: true,
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    category: 'core',
    primaryMuscles: ['core (anti-rotation)', 'obliques', 'transverse abdominis'],
    secondaryMuscles: ['shoulders', 'glutes'],
    equipment: ['cable machine' | 'resistance band'],
    difficulty: 'intermediate',
    instructions: 'Stand beside a cable machine or band anchored at chest height, holding the handle with both hands at the chest. Brace core. Press hands straight out in front, resisting the rotation force from the cable/band. Hold briefly, return to chest.',
    commonMistakes: ['Letting the torso rotate toward the cable (not resisting)', 'Using too much weight', ' Standing too far or too close (altering the leverage)', 'Not bracing the core'],
    substitutions: ['side-plank', 'bird-dog', 'dead-bug'],
    videoRef: 'https://exrx.net/Lists/Exercises/Pallof-Press',
    genderNeutral: true,
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    primaryMuscles: ['obliques', 'rectus abdominis'],
    secondaryMuscles: ['hip flexors'],
    equipment: ['none' | 'medicine ball' | 'dumbbell' | 'plate'],
    difficulty: 'beginner',
    instructions: 'Sit on the floor, knees bent, feet flat or elevated. Hold a weight (or bodyweight) at chest level. Lean back slightly to engage the core. Rotate torso to one side, bringing the weight toward the floor beside the hip. Return to center, rotate to the other side.',
    commonMistakes: ['Using momentum / swinging', 'Not leaning back enough (losing core engagement)', 'Feet not positioned properly', 'Rounding the spine instead of rotating'],
    substitutions: ['woodchop', 'cable-rotation', 'side-plank'],
    videoRef: 'https://exrx.net/Lists/Exercises/Russian-Twist',
    genderNeutral: true,
  },
  {
    id: 'ab-crunch',
    name: 'Ab Crunch (Basic)',
    category: 'core',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: ['obliques'],
    equipment: ['none' | 'mat'],
    difficulty: 'beginner',
    instructions: 'Lie on back, knees bent, feet flat. Place hands behind head (do not interlock, do not pull on the head). Curl the upper back off the floor by contracting the abs, bringing the shoulders toward the hips. Lower with control.',
    commonMistakes: ['Pulling on the neck with the hands', 'Using momentum', 'Lifting the entire back off the floor (hip flexors take over — a crunch only lifts the shoulder blades)', 'Not getting a full contraction at the top'],
    substitutions: ['sit-up', 'bicycle-crunch', 'leg-raise'],
    videoRef: 'https://exrx.net/Lists/Exercises/Crunch',
    genderNeutral: true,
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    category: 'core',
    primaryMuscles: ['rectus abdominis', 'obliques'],
    secondaryMuscles: ['hip flexors'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Lie on back, hands behind head, knees bent at 90° in tabletop. Bring the right elbow toward the left knee while extending the right leg. Switch sides in a pedaling motion. Move slowly and with control — focus on the rotation and contraction.',
    commonMistakes: ['Using momentum / going too fast', 'Pulling on the neck', 'Not getting the elbow to the opposite knee', 'Not extending the leg fully'],
    substitutions: ['crunch', 'russian-twist', 'plank-with-knee-touch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Bicycle-Crunch',
    genderNeutral: true,
  },
  {
    id: 'leg-raise',
    name: 'Lying Leg Raise',
    category: 'core',
    primaryMuscles: ['hip flexors', 'lower rectus abdominis', 'deep core'],
    secondaryMuscles: ['quads'],
    equipment: ['none' | 'mat'],
    difficulty: 'intermediate',
    instructions: 'Lie on back, legs straight, arms at sides or under the glutes for support. Keeping legs straight (or with a slight bend if hamstrings are tight), raise legs until they are perpendicular to the floor (or as high as you can without the lower back arching). Lower with control.',
    commonMistakes: ['Lower back arching off the floor (the key error — stop lowering when the back starts to lift)', 'Bending the knees too much (unless needed for mobility)', 'Using momentum', 'Not controlling the descent'],
    substitutions: ['dead-bug', 'hanging-leg-raise', 'plank'],
    videoRef: 'https://exrx.net/Lists/Exercises/Lying-Leg-Raise',
    genderNeutral: true,
  },
  {
    id: 'plank-with-shoulder-tap',
    name: 'Plank with Shoulder Tap',
    category: 'core',
    primaryMuscles: ['core (anti-rotation)', 'shoulders', 'glutes'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Start in a high plank position (push-up position). Keep hips as still as possible. Tap one shoulder with the opposite hand, then return. Alternate sides. The goal is to minimize hip movement.',
    commonMistakes: ['Hips swaying / rotating', 'Raising the hips too high', 'Going too fast', 'Not keeping a straight plank line'],
    substitutions: ['plank', 'bird-dog', 'pallof-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Plank-Shoulder-Tap',
    genderNeutral: true,
  },
  {
    id: 'ab-wheel-roll-out',
    name: 'Ab Wheel Rollout',
    category: 'core',
    primaryMuscles: ['deep core (transverse abdominis)', 'rectus abdominis'],
    secondaryMuscles: ['shoulders', 'lats (stabilizer)', 'hip flexors'],
    equipment: ['ab wheel'],
    difficulty: 'advanced',
    instructions: 'Kneel on a mat holding an ab wheel in front. Brace the core hard. Roll the wheel forward, extending the body as far as you can while keeping the back flat and hips from sagging. Use the core to pull back to the start.',
    commonMistakes: ['Hips sagging / lower back arching (the main danger)', 'Going too far too soon', 'Using the arms instead of the core to return', 'Not bracing hard enough before starting'],
    substitutions: ['plank', 'dead-bug', 'pallof-press', 'band-roll-out'],
    videoRef: 'https://exrx.net/Lists/Exercises/Ab-Wheel-Rollout',
    genderNeutral: true,
  },

  // ─── MOBILITY / WARMUP ────────────────────────────────────────────────
  {
    id: 'cat-cow',
    name: 'Cat-Cow Stretch',
    category: 'mobility',
    primaryMuscles: ['spine (mobility)', 'core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Start on all fours. Inhale, drop the belly, lift the head and tailbone (cow). Exhale, round the back, tuck the chin and tailbone (cat). Move slowly through the range of motion, focusing on spinal segmentation.',
    commonMistakes: ['Moving too fast', 'Only moving from the shoulders or hips instead of the spine', 'Not breathing with the movement'],
    substitutions: ['child-pos', 'spine-windlass'],
    videoRef: 'https://exrx.net/Lists/Exercises/Cat-Cow',
    genderNeutral: true,
  },
  {
    id: 'world-s-greatest-stretch',
    name: 'World\'s Greatest Stretch',
    category: 'mobility',
    primaryMuscles: ['hips (flexors, rotators)', 'thoracic spine', 'hamstrings'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Step forward into a deep lunge. Place the opposite hand on the floor inside the front foot. Rotate the torso, reaching the same-side arm toward the ceiling. Return the hand to the floor. Straighten the front leg and fold toward the front foot (hamstring stretch). Return to standing. Repeat on the other side.',
    commonMistakes: ['Not going deep enough in the lunge', 'Rushing through the movements', 'Upper back rounding instead of rotating', 'Front knee caving'],
    substitutions: ['lunge-with-rotation', 'cat-cow', 'hip-flexor-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Worldds-Greatest-Stretch',
    genderNeutral: true,
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['hip flexors (psoas, iliacus)', 'rectus femoris'],
    secondaryMuscles: ['glutes (of the stretching side)'],
    equipment: ['none' | 'mat'],
    difficulty: 'beginner',
    instructions: 'Kneel on one knee (use a pad), the other foot forward in a lunge position. Keep the torso upright. Gently push the hips forward until a stretch is felt in the front of the hip of the kneeling leg. Squeeze the glute of the kneeling leg to deepen the stretch. Hold.',
    commonMistakes: ['Arching the lower back (instead of squeezing the glute)', 'Leaning too far forward', 'Not going deep enough in the lunge', 'Holding breath'],
    substitutions: ['world-s-greatest-stretch', 'couch-stretch', 'lunge'],
    videoRef: 'https://exrx.net/Lists/Exercises/Hip-Flexor-Stretch',
    genderNeutral: true,
  },
  {
    id: 'couch-stretch',
    name: 'Couch Stretch',
    category: 'mobility',
    primaryMuscles: ['hip flexors (deep)', 'rectus femoris', 'quads'],
    secondaryMuscles: ['thoracic spine'],
    equipment: ['wall' | 'couch'],
    difficulty: 'intermediate',
    instructions: 'Kneel with one knee against a wall/couch corner, shin vertical against the wall. The other foot is in front in a lunge position. Squeeze the glute of the kneeling leg and keep the torso upright. A deep stretch should be felt in the front of the hip and thigh. Hold. Switch sides.',
    commonMistakes: ['Lower back arching', 'Knee not close enough to the wall', 'Not squeezing the glute', 'Too intense — use a less aggressive hip flexor stretch first'],
    substitutions: ['hip-flexor-stretch', 'world-s-greatest-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Couch-Stretch',
    genderNeutral: true,
  },
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose (Yoga)',
    category: 'mobility',
    primaryMuscles: ['glutes', 'hip external rotators', 'hip flexors (of the back leg)'],
    secondaryMuscles: ['groin'],
    equipment: ['none' | 'mat'],
    difficulty: 'intermediate',
    instructions: 'From all fours, bring one knee forward and place it behind the wrist of the same side, shin angled across the body. Extend the other leg behind you. Fold forward over the front leg (or stay upright). A deep glute and hip stretch should be felt. Hold. Switch sides.',
    commonMistakes: ['Knee pain (adjust the angle or use a figure-4 stretch instead)', 'Hips not square to the front', 'Upper back rounding excessively', 'Not breathing'],
    substitutions: ['figure-4-stretch', 'frog-pose', 'hip-flexor-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Pigeon-Pose',
    genderNeutral: true,
  },
  {
    id: 'figure-4-stretch',
    name: 'Figure-4 Stretch (Supine)',
    category: 'mobility',
    primaryMuscles: ['glutes', 'hip external rotators'],
    secondaryMuscles: ['lower back'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie on back, knees bent, feet flat. Cross one ankle over the opposite knee. Reach through and hold the thigh of the bottom leg, gently pulling it toward you until a stretch is felt in the glute/hip of the crossed leg. Hold. Switch sides.',
    commonMistakes: ['Pulling too hard and rounding the back', 'Not getting a deep enough stretch', 'Knee of the crossed leg not relaxed'],
    substitutions: ['pigeon-pose', 'piriformis-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Figure-4-Stretch',
    genderNeutral: true,
  },
  {
    id: 'child-pos',
    name: 'Child\'s Pose',
    category: 'mobility',
    primaryMuscles: ['lower back', 'hips', 'shoulders'],
    secondaryMuscles: ['glutes'],
    equipment: ['none' | 'mat'],
    difficulty: 'beginner',
    instructions: 'Kneel on the floor, big toes touching, knees spread wide. Sit back on the heels and fold forward, resting the forehead on the floor and arms extended forward (or alongside the body). Relax and breathe into the back and hips.',
    commonMistakes: ['Not spreading the knees enough (for a deeper hip stretch)', 'Upper back rounding too much (if the goal is back relaxation, that\'s fine — adjust based on intent)', 'Not breathing into the stretch'],
    substitutions: ['cat-cow', 'pigeon-pose'],
    videoRef: 'https://exrx.net/Lists/Exercises/Child-s-Pose',
    genderNeutral: true,
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Spine Rotation (Open Book)',
    category: 'mobility',
    primaryMuscles: ['thoracic spine (rotation)'],
    secondaryMuscles: ['shoulders', 'chest'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie on your side, knees bent at 90°, stacked. Arms extended in front, palms together. Open the top arm like a book, rotating the upper back to bring the arm across the body and toward the floor behind you. Follow with the eyes. Keep knees together. Return to start.',
    commonMistakes: ['Knees separating (losing the lower body anchor)', 'Not rotating the upper back — only moving the arm', 'Going too fast', 'Holding breath'],
    substitutions: ['world-s-greatest-stretch', 'cat-cow'],
    videoRef: 'https://exrx.net/Lists/Exercises/Thoracic-Rotation',
    genderNeutral: true,
  },

  // ─── CARDIO / METCON / PLYOMETRIC ─────────────────────────────────────
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['calves', 'cardiovascular system'],
    secondaryMuscles: ['shoulders', 'core', 'quadriceps'],
    equipment: ['jump rope'],
    difficulty: 'beginner',
    instructions: 'Hold rope handles at waist height. Swing the rope overhead using wrist rotation (not the whole arm). Jump lightly, landing on the balls of the feet, just high enough to clear the rope. Keep elbows close to the body. Maintain a steady rhythm.',
    commonMistakes: ['Jumping too high', 'Using the arms instead of the wrists to turn the rope', 'Heels slamming down', 'Elbows flaring out', 'Looking down too much'],
    substitutions: ['high-knees', 'jogging-in-place', 'burpees'],
    videoRef: 'https://exrx.net/Lists/Exercises/Jump-Rope',
    genderNeutral: true,
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'plyometric',
    primaryMuscles: ['full body (cardio + strength)', 'quadriceps', 'chest', 'shoulders', 'triceps', 'core'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'From standing, drop into a squat, place hands on the floor. Jump or step the feet back into a plank. (Optional: do a push-up.) Jump or step the feet back to the squat position. Jump up, reaching arms overhead. Land softly and repeat.',
    commonMistakes: ['Skipping the push-up (if prescribed) or doing it with bad form', 'Jumping the feet back too wide (hip mobility issue)', 'Not jumping high enough at the top', 'Landing with straight legs (soft knees on landing)', 'Going too fast and losing form'],
    substitutions: ['jump-squat', ' squat-thrust', 'mountain-climber'],
    videoRef: 'https://exrx.net/Lists/Exercises/Burpee',
    genderNeutral: true,
  },
  {
    id: 'jump-squat',
    name: 'Jump Squat',
    category: 'plyometric',
    primaryMuscles: ['quadriceps', 'glutes', 'calves', 'hamstrings'],
    secondaryMuscles: ['core', 'cardiovascular system'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Perform a squat down to parallel or as mobility allows. Explode up into a jump, landing softly with knees bent (absorbing the impact). Immediately go into the next rep. Keep the chest up and core braced.',
    commonMistakes: ['Landing with straight legs (joint stress)', 'Knees caving in on landing', 'Not going deep enough on the squat', 'Heels touching down between reps', 'Rounding the back at the bottom'],
    substitutions: ['squat', 'box-jump', 'broad-jump'],
    videoRef: 'https://exrx.net/Lists/Exercises/Jump-Squat',
    genderNeutral: true,
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    category: 'plyometric',
    primaryMuscles: ['quadriceps', 'glutes', 'calves'],
    secondaryMuscles: ['core', 'hamstrings'],
    equipment: ['box' | 'platform'],
    difficulty: 'intermediate',
    instructions: 'Stand facing a box, feet shoulder-width. Squat down slightly, then explode up and forward, landing on the box with both feet. Land softly with knees bent. Stand up fully on the box. Step down (do not jump down — reduces impact).',
    commonMistakes: ['Jumping down from the box (high impact)', 'Landing with knees caved in', 'Not landing softly', 'Choosing a box too high (hip mobility issue on landing)', 'Not standing fully on top before stepping down'],
    substitutions: ['jump-squat', 'step-ups', 'broad-jump'],
    videoRef: 'https://exrx.net/Lists/Exercises/Box-Jump',
    genderNeutral: true,
  },
  {
    id: 'broad-jump',
    name: 'Standing Broad Jump',
    category: 'plyometric',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings', 'calves'],
    secondaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Stand with feet shoulder-width. Swing arms back, then forward as you explode forward into a long jump, landing on both feet. Absorb the landing with bent knees and hips. Reset between reps.',
    commonMistakes: ['Landing with straight legs', 'Knees caving on landing', 'Not using the arms for momentum', 'Not resetting fully between reps'],
    substitutions: ['jump-squat', 'box-jump', 'single-leg-hop'],
    videoRef: 'https://exrx.net/Lists/Exercises/Broad-Jump',
    genderNeutral: true,
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'cardio',
    primaryMuscles: ['core', 'shoulders', 'cardiovascular system'],
    secondaryMuscles: ['hip flexors', 'quadriceps'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Start in a high plank position. Drive one knee toward the chest, then quickly switch legs, as if running in place. Keep the hips low and the core braced. Move at a pace that maintains form.',
    commonMistakes: ['Hips rising too high (piked)', 'Hips sagging', 'Bouncing the feet (not controlled)', 'Looking up and craning the neck', 'Going so fast that form breaks'],
    substitutions: ['burpee', 'high-knees', 'jogging-in-place'],
    videoRef: 'https://exrx.net/Lists/Exercises/Mountain-Climber',
    genderNeutral: true,
  },
  {
    id: 'high-knees',
    name: 'High Knees (Running in Place)',
    category: 'cardio',
    primaryMuscles: ['cardiovascular system', 'hip flexors', 'quadriceps'],
    secondaryMuscles: ['core', 'calves', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Stand tall, core engaged. Run in place, driving the knees up toward the chest as high as comfortable. Pump the arms. Maintain a quick pace. Land softly on the balls of the feet.',
    commonMistakes: ['Leaning forward (instead of staying tall)', 'Not driving the knees high enough', 'Land with heavy feet', 'Looking down'],
    substitutions: ['jump-rope', 'mountain-climber', 'jogging-in-place'],
    videoRef: 'https://exrx.net/Lists/Exercises/High-Knees',
    genderNeutral: true,
  },
  {
    id: 'jogging-in-place',
    name: 'Jogging in Place',
    category: 'cardio',
    primaryMuscles: ['cardiovascular system'],
    secondaryMuscles: ['quadriceps', 'hamstrings', 'calves', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Jog in place at a steady, moderate pace. Keep the core lightly engaged, shoulders relaxed, and arms pumping naturally. Land softly. Use as a warm-up or low-intensity cardio interval.',
    commonMistakes: ['Heel striking heavily', 'Shoulders tensing up', 'Not staying tall'],
    substitutions: ['high-knees', 'jump-rope'],
    videoRef: 'https://exrx.net/Lists/Exercises/Jog-in-Place',
    genderNeutral: true,
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'plyometric',
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['core', 'shoulders', 'grip'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    instructions: 'Stand with the kettlebell on the floor in front of you. Hinge at the hips, slight knee bend, back flat. Grip the kettlebell. Swing it back between the legs (loaded hamstring position). Explosively drive the hips forward, swinging the kettlebell up to chest/shoulder height (the arms are just along for the ride — the power comes from the hips). Let it swing back down and repeat.',
    commonMistakes: ['Squatting instead of hinging', 'Using the arms to lift the kettlebell (turning it into an overhead press)', 'Rounding the back', 'Not getting the kettlebell high enough (hip power lacking)', 'Drops the kettlebell on the forward swing'],
    substitutions: ['deadlift', 'romanian-deadlift', 'jump-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Kettlebell-Swing',
    genderNeutral: true,
  },
  {
    id: 'squat-thrust',
    name: 'Squat Thrust (Burpee without the jump / push-up)',
    category: 'cardio',
    primaryMuscles: ['quadriceps', 'shoulders', 'core', 'cardiovascular system'],
    secondaryMuscles: ['chest', 'triceps', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'From standing, squat down and place hands on the floor. Jump or step the feet back into a plank. Jump or step the feet back to the squat position. Stand up. Repeat. A simpler version of the burpee without the vertical jump or push-up.',
    commonMistakes: ['Hips sagging in the plank', 'Jumping the feet too wide', 'Not resetting between reps', 'Going too fast and losing form'],
    substitutions: ['burpee', ' mountain-climber', 'jump-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Squat-Thrust',
    genderNeutral: true,
  },

  // ─── MINIMAL/EQUIPMENT-FREE STRENGTH ──────────────────────────────────
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Stand with feet shoulder-width, toes slightly out. Brace core. Squat down by bending hips and knees, keeping chest up and weight in the middle of the feet. Descend as deep as mobility allows. Drive through the mid-foot to stand.',
    commonMistakes: ['Heels lifting', 'Knees caving in', 'Rounding the back', 'Not going deep enough', 'Rising onto toes'],
    substitutions: ['goblet-squat', 'leg-press', 'chair-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Squat',
    genderNeutral: true,
  },
  {
    id: 'chair-squat',
    name: 'Chair / Box Squat',
    category: 'strength',
    primaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    secondaryMuscles: ['core'],
    equipment: ['chair' | 'box'],
    difficulty: 'beginner',
    instructions: 'Stand in front of a chair or box, feet shoulder-width. Squat down by bending hips and knees, sitting back onto the chair/box (lightly touching it, not collapsing onto it). Stand back up by driving through the feet. Use this to learn proper squat depth and hip hinge.',
    commonMistakes: ['Collapsing onto the chair (losing tension)', 'Knees caving in', 'Heels lifting', 'Not standing all the way up'],
    substitutions: ['bodyweight-squat', 'goblet-squat', 'box-squat-with-weight'],
    videoRef: 'https://exrx.net/Lists/Exercises/Box-Squat',
    genderNeutral: true,
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'endurance',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['wall'],
    difficulty: 'beginner',
    instructions: 'Lean against a wall with the back flat. Slide down until knees are bent at ~90° (or as deep as comfortable). Hold the position, keeping the back against the wall and core engaged. Do not let the knees cave in.',
    commonMistakes: ['Knees going past the toes excessively (depends on individual anatomy)', 'Lower back not against the wall', 'Knees caving in', 'Holding breath'],
    substitutions: ['bodyweight-squat', 'leg-press', 'split-squat'],
    videoRef: 'https://exrx.net/Lists/Exercises/Wall-Sit',
    genderNeutral: true,
  },
  {
    id: 'tricep-dip-bench',
    name: 'Tricep Dip (on Bench / Chair)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['anterior deltoids'],
    equipment: ['bench', 'chair'],
    difficulty: 'intermediate',
    instructions: 'Same as bench dip. Sit on edge, hands beside hips. Slide forward, legs bent or straight. Lower by bending elbows to ~90°, pressing back up. Keep shoulders back and down.',
    commonMistakes: ['Shoulders rolling forward at the bottom', 'Going too deep', 'Using momentum'],
    substitutions: ['dip', 'tricep-push-down', 'close-grip-bench-press'],
    videoRef: 'https://exrx.net/Lists/Exercises/Tricep-Dip',
    genderNeutral: true,
  },
  {
    id: 'inverted-row-under-table',
    name: 'Inverted Row (under a sturdy table)',
    category: 'strength',
    primaryMuscles: ['latissimus dorsi', 'rhomboids', 'middle trapezius'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['sturdy table' | 'bar'],
    difficulty: 'intermediate',
    instructions: 'Lie under a sturdy table or bar. Grip the edge/bar. Pull the chest up toward it, keeping the body straight. Lower with control. Only use a table that is solid and can support the weight safely.',
    commonMistakes: ['Using an unstable surface', 'Hips sagging', 'Not getting the chest to the bar/table', 'Using momentum'],
    substitutions: ['inverted-row', 'pull-up', 'lat-pulldown'],
    videoRef: 'https://exrx.net/Lists/Exercises/Inverted-Row',
    genderNeutral: true,
  },
  {
    id: 'plank-up-down',
    name: 'Plank Up-Down (Plank to Push-Up)',
    category: 'core',
    primaryMuscles: ['core', 'shoulders', 'triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: 'Start in a forearm plank. Push up onto one hand, then the other, into a high plank (push-up position). Lower back down to the forearms, one arm at a time. Alternate which arm goes first. Keep the hips as still as possible throughout.',
    commonMistakes: ['Hips rotating', 'Hips sagging', 'Going too fast and losing form', 'Not keeping a straight line'],
    substitutions: ['plank', 'push-up', 'shoulder-tap-plank'],
    videoRef: 'https://exrx.net/Lists/Exercises/Plank-Up-Down',
    genderNeutral: true,
  },

  // ─── STRETCHING / COOL DOWN ────────────────────────────────────────────
  {
    id: 'hamstring-stretch-seated',
    name: 'Seated Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings', ' calves'],
    secondaryMuscles: ['lower back'],
    equipment: ['none' | 'mat'],
    difficulty: 'beginner',
    instructions: 'Sit on the floor with one leg extended and the other bent (foot against the inner thigh of the extended leg). Keep the back as straight as possible and hinge forward at the hips toward the extended foot. A stretch should be felt in the hamstring. Hold. Switch legs.',
    commonMistakes: ['Rounding the back to reach the foot (the goal is a hamstring stretch, not touching the toe)', 'Bending the extended knee', 'Not hinging from the hips'],
    substitutions: ['standing-hamstring-stretch', 'world-s-greatest-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Seated-Hamstring-Stretch',
    genderNeutral: true,
  },
  {
    id: 'standing-hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    category: 'mobility',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [' calves', 'lower back'],
    equipment: ['none' | 'step'],
    difficulty: 'beginner',
    instructions: 'Stand with one heel on a low step or the floor, toes pointing up. Keep the back straight and hinge forward slightly at the hips until a stretch is felt in the hamstring of the extended leg. Hold. Switch legs.',
    commonMistakes: ['Rounding the back', 'Bending the standing knee too much', 'Not hinging from the hips'],
    substitutions: ['seated-hamstring-stretch', 'downward-dog'],
    videoRef: 'https://exrx.net/Lists/Exercises/Standing-Hamstring-Stretch',
    genderNeutral: true,
  },
  {
    id: 'chest-stretch-doorway',
    name: 'Doorway Chest Stretch',
    category: 'mobility',
    primaryMuscles: ['pectorals', 'anterior deltoids'],
    secondaryMuscles: [],
    equipment: ['doorway'],
    difficulty: 'beginner',
    instructions: 'Stand in a doorway. Place forearms on the doorframe at shoulder height, elbows bent at 90°. Step one foot through the doorway and gently lean forward until a stretch is felt in the chest and front of the shoulders. Hold. Adjust elbow height to target different parts of the chest.',
    commonMistakes: ['Elbows too high (shoulder strain) or too low', 'Leaning too far (shoulder joint stress)', 'Not stepping through enough'],
    substitutions: ['chest-stretch-on-floor', 'cross-body-shoulder-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Doorway-Pectoral-Stretch',
    genderNeutral: true,
  },
  {
    id: 'cross-body-shoulder-stretch',
    name: 'Cross-Body Shoulder Stretch',
    category: 'mobility',
    primaryMuscles: ['posterior deltoids', 'upper trapezius'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Stand or sit. Pull one arm across the chest with the opposite hand, just below the elbow. Keep the shoulder of the stretched arm down (do not let it shrug up). Hold. Switch arms.',
    commonMistakes: ['Pulling on the elbow joint instead of the arm', 'Shoulder shrugging up', 'Not holding long enough'],
    substitutions: ['doorway-chest-stretch', ' tricep-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Cross-Body-Shoulder-Stretch',
    genderNeutral: true,
  },
  {
    id: 'tricep-stretch',
    name: 'Tricep Stretch (Overhead)',
    category: 'mobility',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['latissimus dorsi'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Stand or sit. Raise one arm overhead, bend the elbow so the hand touches the middle of the back. Use the opposite hand to gently press on the elbow, deepening the stretch. Hold. Switch arms.',
    commonMistches: ['Pulling on the neck', 'Arching the lower back to get the arm behind the head', 'Not keeping the elbow close to the head'],
    substitutions: ['cross-body-shoulder-stretch', 'chest-stretch-doorway'],
    videoRef: 'https://exrx.net/Lists/Exercises/Tricep-Stretch',
    genderNeutral: true,
  },
  {
    id: 'quad-stretch-standing',
    name: 'Standing Quad Stretch',
    category: 'mobility',
    primaryMuscles: ['quadriceps', 'hip flexors'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Stand tall (hold onto a wall or chair for balance if needed). Bend one knee, bringing the heel toward the glute. Grab the ankle with the same-side hand. Gently pull the heel closer. Keep the knees close together and the torso upright. Hold. Switch legs.',
    commonMistakes: ['Knee splaying out to the side', 'Arching the lower back', 'Leaning forward', 'Pulling too hard on the knee joint'],
    substitutions: ['lying-quad-stretch', 'hip-flexor-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Standing-Quad-Stretch',
    genderNeutral: true,
  },
  {
    id: 'lying-quad-stretch',
    name: 'Lying Quad Stretch',
    category: 'mobility',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: 'Lie on your side (or stomach). Bend the top knee and grab the ankle with the hand. Gently pull the heel toward the glute. Keep the knees together and the hips stable. Hold. Switch sides.',
    commonMistakes: ['Knee splaying', 'Hips rolling backward', 'Pulling too hard'],
    substitutions: ['standing-quad-stretch'],
    videoRef: 'https://exrx.net/Lists/Exercises/Quad-Stretch',
    genderNeutral: true,
  },
  {
    id: 'calf-stretch-wall',
    name: 'Wall Calf Stretch',
    category: 'mobility',
    primaryMuscles: ['gastrocnemius', 'soleus'],
    secondaryMuscles: [],
    equipment: ['wall'],
    difficulty: 'beginner',
    instructions: 'Stand facing a wall. Place hands on the wall. Step one foot back, keeping the leg straight (for gastrocnemius) and the heel on the ground. Lean into the wall until a stretch is felt in the calf. To stretch the soleus, bend the back knee slightly while keeping the heel down. Hold. Switch legs.',
    commonMistakes: ['Heel lifting off the ground', 'Back foot not pointing straight forward', 'Not going deep enough', 'Rounding the back'],
    substitutions: ['downward-dog', 'calve-raise (stretch portion)'],
    videoRef: 'https://exrx.net/Lists/Exercises/Calf-Stretch',
    genderNeutral: true,
  },
  {
    id: 'downward-dog',
    name: 'Downward-Facing Dog (Yoga)',
    category: 'mobility',
    primaryMuscles: ['hamstrings', 'calves', 'shoulders', 'chest', 'back'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['none' | 'mat'],
    difficulty: 'intermediate',
    instructions: 'Start on all fours. Tuck toes, lift hips up and back, straightening the legs (heels can be off the ground — that\'s fine). Press the chest toward the knees, lengthen the spine, and relax the head. Pedal the feet (bend one knee at a time) to stretch the hamstrings alternately.',
    commonMistakes: ['Rounding the upper back (push the floor away and lift the chest)', 'Heels forced to the ground (not necessary — hamstring flexibility varies)', 'Head hanging without intention', 'Weight all in the hands (distribute to the hips)'],
    substitutions: ['child-pos', 'standing-hamstring-stretch', 'pigeon-pose'],
    videoRef: 'https://exrx.net/Lists/Exercises/Downward-Facing-Dog',
    genderNeutral: true,
  },
];

export const EXERCISE_BY_ID: Record<string, Exercise> = Object.fromEntries(
  EXERCISE_LIBRARY.map(e => [e.id, e])
);

export const EXERCISES_BY_CATEGORY: Record<string, Exercise[]> = EXERCISE_LIBRARY.reduce(
  (acc, e) => {
    if (!acc[e.category]) acc[e.category] = [];
    acc[e.category].push(e);
    return acc;
  },
  {} as Record<string, Exercise[]>
);

export const EXERCISES_BY_MUSCLE: Record<string, Exercise[]> = EXERCISE_LIBRARY.reduce(
  (acc, e) => {
    for (const muscle of e.primaryMuscles) {
      if (!acc[muscle]) acc[muscle] = [];
      acc[muscle].push(e);
    }
    return acc;
  },
  {} as Record<string, Exercise[]>
);

export const EXERCISES_BY_EQUIPMENT: Record<string, Exercise[]> = EXERCISE_LIBRARY.reduce(
  (acc, e) => {
    for (const eq of e.equipment) {
      if (!acc[eq]) acc[eq] = [];
      acc[eq].push(e);
    }
    return acc;
  },
  {} as Record<string, Exercise[]>
);

export function searchExercises(query: string): Exercise[] {
  const q = query.toLowerCase();
  return EXERCISE_LIBRARY.filter(
    e =>
      e.name.toLowerCase().includes(q) ||
      e.primaryMuscles.some(m => m.toLowerCase().includes(q)) ||
      e.category.toLowerCase().includes(q) ||
      e.equipment.some(eq => eq.toLowerCase().includes(q))
  );
}

export function getSubstituteExercises(exerciseId: string): Exercise[] {
  const exercise = EXERCISE_BY_ID[exerciseId];
  if (!exercise) return [];
  return exercise.substitutions
    .map(id => EXERCISE_BY_ID[id])
    .filter(Boolean) as Exercise[];
}

export function getExercisesByEquipment(availableEquipment: string[]): Exercise[] {
  return EXERCISE_LIBRARY.filter(e =>
    e.equipment.every(eq => availableEquipment.includes(eq))
  );
}

export function getExercisesByMuscleTarget(muscle: string, availableEquipment: string[]): Exercise[] {
  return EXERCISES_BY_MUSCLE[muscle]?.filter(e =>
    e.equipment.every(eq => availableEquipment.includes(eq))
  ) || [];
}

export const EXERCISE_COUNT = EXERCISE_LIBRARY.length;
